### ISSUE TITLE
Working with a non-closed track

### ISSUE THREAD

**Issue by psychemedia** [TUMFTM/laptime-simulation#1]
Is there a simple way of tweaking this package so that it runs with a non-closed track (eg as in a sprint or rally stage)?

I note that if the track is broken, the algorithm currently tries to close it with a straight line connecting the gap.

**Comment by heilmeiera** [comment]
To make it work with an open track you have to rework a few parts of the solver. For example, the solver actually solves two laps to determine the correct start velocity at the beginning of the lap, which depends on the track layout in front of the finish line (this is a simple solution and could be done more efficient of course). In general, this is not an overly complicated task, but requires a few hours of work which I cannot afford at the moment. If you do the work, I would appreciate a pull request :)

**Comment by psychemedia** [comment]
Okay, thanks... I'll try to have a look at the code if I get a chance, but this is not the sort of code I've ever looked at before, so it could take some time for me to understand how laptime simulation works at all, let alone try to make changes to it..

**Comment by heilmeiera** [comment]
For getting a bit of an idea of how the LTS works in general, you could have a look into the paper mentioned in the Readme. Regarding the code: I tried to make lots of comments, but for sure it's not easy to get into someone else's code, that's true. Let me know if you are stuck.
